#!/bin/bash
sudo su
yum update -y
yum install -y httpd
cd /var/www/html
wget https://github.com/werkmanne/fitapp-website/archive/refs/heads/main.zip
unzip main.zip
unzip /var/www/html/fitapp-website-main/fitapp-webstie.zip
rm -rf main.zip fitapp-website-main
systemctl enable httpd 
systemctl start httpd
